# -*- coding: utf-8 -*-
"""Text_to_image_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IGy6mjnTNzVWOMm62f0ndnfjgBFyRu1

Summary

This notebook performs the following actions:

1.Setup: Installs the required Python libraries for text-to-image generation.

2.Model Loading: Downloads and loads a pre-trained Stable Diffusion model from  the Hugging Face Hub.

3.Input: Takes a text prompt from the user.

4.Image Generation: Uses the provided prompt to generate an image.
Display: Shows the generated image.

Step 1: Installing Necessary Libraries
"""

!pip install diffusers transformers accelerate --upgrade
!pip install safetensors

"""Step 2: Importing Libraries"""

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

"""Step 3: Authenticating with Hugging Face Hub"""

from huggingface_hub import login
login("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")  # Paste your token here

"""Step 4: Loading the Stable Diffusion Model"""

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True
)
pipe = pipe.to("cuda")

"""Step 5: Getting the User's Text Prompt"""

user_prompt = input("Enter your image prompt: ")

"""Step 6: Generating and Displaying the Image"""

image = pipe(user_prompt).images[0]

# Display the generated image
plt.imshow(image)
plt.axis("off")
plt.title("Generated Image")
plt.show()